### ISSUE TITLE
we need more help with setting it up please

### ISSUE THREAD

**Issue by Mago126** [ulnk/scam#2]
so whats "mongo_url" i do not understand that thing with echo "token" and "mongo" do i have to put in my discord bot token and mongo api url? if yes i did it and this error code keep popping up

 C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\connection.js:689
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\connection.js:689:11)
    at C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\index.js:378:10
    at C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\index.js:1223:10)
    at Mongoose.connect (C:\Users\saidmago\Desktop\scam-main\node_modules\mongoose\lib\index.js:377:20)
    at C:\Users\saidmago\Desktop\scam-main\src\index.ts:11:20
    at Object.<anonymous> (C:\Users\saidmago\Desktop\scam-main\src\index.ts:16:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
[nodemon] app crashed - waiting for file changes before starting...
![image](https://user-images.githubusercontent.com/106020383/178160482-2697173a-3826-4cf9-9d18-790ab2fe1200.png)

**Comment by ulnk** [comment]
Your .ENV is misconfigured
![image](https://user-images.githubusercontent.com/93608862/178160778-71cff601-ca6a-468a-b17e-593d211fd625.png)

**Comment by ulnk** [comment]
https://account.mongodb.com/account/register
