### ISSUE TITLE
Cant Run

### ISSUE THREAD

**Issue by 7z-henry** [ulnk/scam#26]
C:\Users\henry\Documents\scam-main\scam-main>npm run start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> new-scam@0.0.0 start
> ts-node src/index.ts

[12:59:15] [*] INTERACTIONCREATE EVENT LOADED
[12:59:15] [*] READY EVENT LOADED
[12:59:15] [*] DISCORD BOT LOADED
C:\Users\henry\Documents\scam-main\scam-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^
Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\henry\Documents\scam-main\scam-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\henry\Documents\scam-main\scam-main\node_modules\discord.js\src\client\Client.js:232:7) {
  [Symbol(code)]: 15
}

**Comment by ulnk** [comment]
from `README.md`
> - **Create a new Discord Bot**
    - Enable all intents for the bot
Please read before making issues. Also do not check requires code oauth2

**Comment by 7z-henry** [comment]
not working

**Comment by ulnk** [comment]
@7z-henry what was your fix
