### ISSUE TITLE
Bot crashes after pulling token

### ISSUE THREAD

**Issue by Markusklarcus1** [ulnk/scam#27]
After the bot pulls the token it crashes and gives this log
```
C:\Users\PC\scam\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:479
                                throw new DiscordAPIError(data, 'code' in data ? data.code : data.error, status, method, url, requestData);
          ^
DiscordAPIError[50013]: Missing Permissions
    at SequentialHandler.runRequest (C:\Users\PC\scam\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:479:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\PC\scam\node_modules\@discordjs\rest\src\lib\handlers\SequentialHandler.ts:204:11)
    at async REST.request (C:\Users\PC\scam\node_modules\@discordjs\rest\src\lib\REST.ts:341:20)
    at async GuildMemberRoleManager.add (C:\Users\PC\scam\node_modules\discord.js\src\managers\GuildMemberRoleManager.js:129:7) {
  rawError: { message: 'Missing Permissions', code: 50013 },
  code: 50013,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/guilds/1006262692157333655/members/363692233964257292/roles/1006262932960714812',
  requestBody: { files: undefined, json: undefined }
```

**Comment by ulnk** [comment]
lots of people are getting this issue

**Comment by ulnk** [comment]
hope fix
