### ISSUE TITLE
Error with index.ts

### ISSUE THREAD

**Issue by TheBogler** [ulnk/scam#32]
Hi! I had a bug or something, or I do not know what. Help please

```
scpuser@scpserv:~/tss/src$ npm run start

> new-scam@0.0.0 start /home/scpuser/tss
> ts-node src/index.ts

/home/scpuser/tss/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
{ TSError: ⨯ Unable to compile TypeScript:
src/discord/discordClient.ts:1:18 - error TS2305: Module '"discord.js"' has no exported member 'Partials'.

1 import { Client, Partials } from "discord.js";
                   ~~~~~~~~
src/discord/discordClient.ts:9:9 - error TS2345: Argument of type '{ intents: number; partials: any[]; allowedMentions: { parse: ("roles" | "users" | "everyone")[]; }; }' is not assignable to parameter of type 'ClientOptions'.
  Object literal may only specify known properties, and 'intents' does not exist in type 'ClientOptions'.

9         intents: 131071,
          ~~~~~~~~~~~~~~~

    at createTSError (/home/scpuser/tss/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/scpuser/tss/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/scpuser/tss/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/scpuser/tss/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/scpuser/tss/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/scpuser/tss/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) diagnosticCodes: [ 2305, 2345 ] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! new-scam@0.0.0 start: `ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the new-scam@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scpuser/.npm/_logs/2022-08-25T11_03_46_187Z-debug.log
```

**Comment by ulnk** [comment]
what version is your discord.js

**Comment by TheBogler** [comment]
v13

**Comment by ulnk** [comment]
`"discord.js": "^14.0.3",`
you need discord js v14
