### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kevincrafturu2** [ulnk/scam#41]
> new-scam@0.0.0 start
> ts-node src/index.ts

[18:56:19] [*] INTERACTIONCREATE EVENT LOADED 
(node:1215) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/home/runner/nope/node_modules/discord.js/src/client/Client.js:214
    if (!token || typeof token !== 'string') throw new Error(ErrorCodes.TokenInvalid);
                                                   ^
Error [TokenInvalid]: An invalid token was provided.
    at Client.login (/home/runner/nope/node_modules/discord.js/src/client/Client.js:214:52)
    at initialise (/home/runner/nope/src/discord/discordClient.ts:13:10)
    at Object.<anonymous> (/home/runner/nope/src/index.ts:8:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/runner/nope/node_modules/ts-node/src/index.ts:1618:23)

**Comment by YourLocalAnomicPIayer** [comment]
it needs to be a bot token

**Comment by kevincrafturu2** [comment]
Yea it is

**Comment by kevincrafturu2** [comment]
But dosent works

**Comment by kevincrafturu2** [comment]
Like i tested in my pc and in my vps and nothing

**Comment by ulnk** [comment]
Your discord bot is either banned or has a new token. This is not an issue with this repo.
