### ISSUE TITLE
Waste of time

### ISSUE THREAD

**Issue by unfairDude** [ulnk/scam#54]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readdir (node:internal/fs/promises:724:10)
    at startFetch (/home/anon/Desktop/scam/src/fetch/startFetch.ts:10:35)
    at Client.callback (/home/anon/Desktop/scam/src/events/Ready.ts:22:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE

Not working, installed Node is and all dependencies

**Comment by unfairDude** [comment]
This retard pushing to use v3 and nothing works

**Comment by unfairDude** [comment]
Tried both windows and Linux machine, different errors, same shit

**Comment by ulnk** [comment]
Damn wait
I can't reply to things straight away

**Comment by ulnk** [comment]
it works for 80 other people
i have fixed the issue
