### ISSUE TITLE
MongoParseError

### ISSUE THREAD

**Issue by WiiZARDD** [ulnk/scam#8]
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongodb-connection-string-url\src\index.ts:133:13)
    at parseOptions (C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongodb\src\connection_string.ts:262:15)
    at new MongoClient (C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongodb\src\mongo_client.ts:347:34)
    at C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongoose\lib\connection.js:796:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongoose\lib\connection.js:793:19)
    at C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongoose\lib\index.js:378:10
    at C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\bisho\OneDrive\Documents\scam-main\scam-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)

**Comment by ulnk** [comment]
## Solved via Discord
**index.ts**
```diff
- if (config.mongoose) 
-       await mongoose.connect(config.mongoose.uri);
+ if (config.mongoose.enabled) 
+       await mongoose.connect(config.mongoose.uri);
```
